---
title: "get_map"
author: "Junna"
date: "5/6/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r package}
rm(list=ls())
gc()

setwd("C:/Users/jnawang/Box/Biodiversity/SDM/")

if(!'dismo' %in% installed.packages()[,"Package"]){
  install.packages('dismo', repos='https://rspatial.r-universe.dev')
}

########################
# Setup
list.of.packages <- c("raster","rgdal","rgeos", "sp",
                      "SDMtune","dismo",
                      "tidyverse",
                      "RSQLite","DBI","odbc",
                      "foreach","doParallel","pbapply","doFuture","future","doRNG", "geodata")

new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]

if(length(new.packages)) install.packages(new.packages)

sapply(list.of.packages, require, character.only = TRUE)

```


```{r get elevation}
#elev <- elevation_global(res = 2.5, path = "C:/Users/jnawang/Box/Biodiversity/data/dem")
elev <- raster("C:/Users/jnawang/Box/Biodiversity/data/dem/wc2.1_2.5m_elev.tif")

# convert to moll coordinate
example <- raster('C:/Users/jnawang/Box/Biodiversity/SDM/preds/bios_pres/bio1.tif')
newproj <- crs(example)
elev <- projectRaster(elev, crs = newproj)

# resample to the same format as bio1.tif
elev <- resample(elev, example, method = 'bilinear', filename='C:/Users/jnawang/Box/Biodiversity/data/dem/elev.tif', overwrite=TRUE)

```


```{r elevation heterogeneity use rugged index}
elev_heter <- raster("C:/work_space/topography/tri_5KMmn_GMTEDmd.tif")
elev_heter <- projectRaster(elev_heter, crs = newproj)
elev_heter <- resample(elev_heter, example, method = 'bilinear', filename='C:/Users/jnawang/Box/Biodiversity/data/dem/elev_heter.tif', overwrite=TRUE)

```


```{r process soil maps, projection and resample}
library(terra)
rm(list=ls())
#
template <- terra::rast('/Users/junnawang/UCDLab/Biodiversity/data/climate/bioclimate_land_only/bio1_remove_lakes.tif')
template <- terra::rast('/Users/junnawang/UCDLab/Biodiversity/SDM/preds/bios_pres/bio1.tif')
crs_moll <- "+proj=moll +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs"
#
depthB <- terra::rast("/Users/junnawang/UCDLab/Biodiversity/data/soil/BulkDensity/bulk_avg.tif")
depthB_aggregate <- terra::aggregate(depthB, fact=4, fun="mean")
# plot(depthB)
depthB_moll <- terra::project(depthB_aggregate, crs_moll)
depthB_moll
#
depthB_moll_5m <- terra::resample(depthB_moll, template)
plot(depthB_moll_5m)
#
# this process is not used, because of many holes in the map. 
#
```



```{r current soil moisture data}

# resample and calculate high-resolution soil moisture
moisture_l <- raster('C:/Users/jnawang/Box/Biodiversity/data/soil_moisture/soilMoisture_ssm-2016-2021.tif')
moisture_r <- raster('C:/Users/jnawang/Box/Biodiversity/data/soil_moisture/soilMoisture_ssm-2016-2021-h.tif')
# this step takes time!
moisture <- merge(moisture_l, moisture_r)
example <- raster('C:/Users/jnawang/Box/Biodiversity/SDM/preds/bios_pres/bio1.tif')
plot(moisture)
plot(example)

# make sure the two have the same projection
newproj <- crs(example)
# the projection takes lots of time!
moisture <- projectRaster(moisture, crs = newproj)
plot(moisture)

# this step also takes time
moisture <- resample(moisture, example, method = 'bilinear', filename='C:/Users/jnawang/Box/Biodiversity/data/soil_moisture/moisture_pres.tif', overwrite=TRUE)

```


```{r soil moisture more time period and merge the above code}
# use simplified code
library(raster)
library(ncdf4)
#
root    <- "C:/Users/jnawang/Box/Biodiversity/data/soil_moisture/"
#
# read readily created present soil moisture
moisture_pres <- raster(paste0(root, 'moisture_pres.tif'))
newproj <- crs(moisture_pres)
#
#
ncfname <- "mrsos_Lmon_CNRM-CM6-1-HR_historical_r1i1p1f2_gr_185001-201412.nc"
mrsos_r <- stack(paste0(root, ncfname))    ## this is a list
# current data 1995-2014
mrsos_95_14 <- mean(mrsos_r[[1741:1980]])
mrsos_95_14 <- rotate(mrsos_95_14)

ssps  <- c("126", "245", "370", "585")
times <- c("2021-2040", "2041-2060", "2061-2080", "2081-2100")

for (itime in 1:length(times)) {
  for (issp in 1:length(ssps)) {
    ncfname <- paste0('mrsos_Lmon_CNRM-CM6-1-HR_ssp', ssps[issp], '_r1i1p1f2_gr_201501-210012.nc')
    mrsos_r <- stack(paste0(root, ncfname))
    mrsos_fut <- mean(mrsos_r[[((6+(itime-1)*20)*12+1):((6+itime*20)*12)]])
    mrsos_fut <- rotate(mrsos_fut)
    # get change ratio
    mrsos_fut <- mrsos_fut / mrsos_95_14
    # proj and resample
    
    mrsos_fut <- projectRaster(mrsos_fut, crs = newproj)
    mrsos_fut <- resample(mrsos_fut, moisture_pres, method = 'bilinear')
    mrsos_fut <- mrsos_fut * moisture_pres
    writeRaster(mrsos_fut, filename=paste0(root, 'moisture_', ssps[issp], '_', times[itime], '.tif'), overwrite=TRUE)
  }
}

```


### map of future land use
```{r future land use change-crop and built}
# this data is from here
#
# https://www.isimip.org/gettingstarted/input-data-bias-adjustment/details/57/
#
# use simplified code
library(raster)
library(ncdf4)

# do build-up first
root    <- "C:/Users/jnawang/Box/Biodiversity/data/"
#
# read readily created present buildings
#
# I only have data for two rcp scenarios: rcp2.6 and rcp6.0; 
# I need absolute change at four time points: 2040, 2060, 2080, 2100, comparing to 2015
# crop: do crop first
# 
# different scenarios
scenarios <- c('crop_ESM_126', 'crop_ESM_245', 'crop_ESM_370', 'crop_ESM_585', 'build_ESM_126', 'build_ESM_245', 'build_ESM_370', 'build_ESM_585')
ncfname   <- c("land_use_coarse/rcp26soc_gfdl-esm2m_landuse-15crops_annual_2006_2099.nc4", 
             "land_use_coarse/rcp26soc_gfdl-esm2m_landuse-15crops_annual_2006_2099.nc4", 
             "land_use_coarse/rcp60soc_gfdl-esm2m_landuse-15crops_annual_2006_2099.nc4", 
             "land_use_coarse/rcp60soc_gfdl-esm2m_landuse-15crops_annual_2006_2099.nc4", 
             "land_use_coarse/rcp26soc_landuse-urbanareas_annual_2006_2099.nc4",
             "land_use_coarse/rcp26soc_landuse-urbanareas_annual_2006_2099.nc4",
             "land_use_coarse/rcp60soc_landuse-urbanareas_annual_2006_2099.nc4",
             "land_use_coarse/rcp60soc_landuse-urbanareas_annual_2006_2099.nc4")
year    <- c(2040, 2060, 2080, 2099)                ## this corresponding to 2040, 2060, 2080, and 2099
#year    <- c(2040)
# 1:length(scenarios)
for (is in 1:length(scenarios)) {
landuse <- raster::stack(paste0(root, ncfname[is]))     ## coverage fraction: 0-1
if (is >= 5) {
  landuse_pres <- raster(paste0(root, 'land_use_fine/build.tif'))    #coverage percent: 0-100
  
} else {
  landuse_pres <- raster(paste0(root, 'land_use_fine/crop.tif'))     #coverage percent: 0-100
}
newproj <- crs(landuse_pres)
plot(landuse_pres)
#
for (iy in year) {
landuse_cfut <- (landuse[[iy-2005]] - landuse[[10]]) * 100
#
landuse_cfut <- rotate(landuse_cfut)
landuse_cfut <- projectRaster(landuse_cfut, crs = newproj)
landuse_cfut <- resample(landuse_cfut, landuse_pres, method = 'bilinear')
landuse_fut  <- landuse_cfut + landuse_pres
# correct for values < 0 and value > 100
landuse_fut[landuse_fut<0.0]   <- 0.0
landuse_fut[landuse_fut>100.0] <- 100.0
if (iy < 2081) {
  writeRaster(landuse_fut, paste0(root, 'land_use_coarse/', scenarios[is], '_', iy-19, '-', iy, '.tif'), overwrite=TRUE)
}
else {
  writeRaster(landuse_fut, paste0(root, 'land_use_coarse/', scenarios[is], '_', iy-18, '-', iy+1, '.tif'), overwrite=TRUE)
}
  
plot(landuse_fut)

}       
}
# in the future, cropland area is going to first increase and then decrease!
# urban area does not change very much! it seems it does not change at all.

# remove all the xml file
file <- list.files(path=paste0(root, 'land_use_coarse/'), pattern='*.aux.xml', full.names=T)
file.remove(file)

```


```{r only for historical climate}
library(raster)
library(geodata)
rm(list=ls())

setwd("C:/Users/jnawang/Box/Biodiversity/")
# directory has to be created step by step!
if(!dir.exists("data/climate/history")){
  dir.create("data/climate/history")
}
# get data
worldclim_global(var = "bio", res = 10, path = "data/climate/history")
worldclim_global(var = "bio", res = 2.5, path = "data/climate/history")

```


```{r get ensemble average and select 3 GCMs}
# the meaning of ensemble average, the average of multiple models.
# references: CMIP1 evaluation and intercomparison of coupled climate models; Lambert & Boer, 2001
# ensemble average was recalculated on 10/5/2025, because old data from worldclimate had a big problem. New data was downloaded and used.
# we found problems with the projection function for ESM images. It is addressed now. 
# this will take 1-2 hours to run. 
library(terra)
rm(list=ls())
#
ssps  <- c("126", "245", "370", "585")
times <- c("2021-2040", "2041-2060", "2061-2080", "2081-2100")                  # only care about one time period
gcms  <- c("ACCESS", "MIROC6", "MPI")
root  <- "/Users/junnawang/UCDLab/Biodiversity/data/climate/future/"
#
template <- terra::rast('/Users/junnawang/UCDLab/Biodiversity/data/climate/bioclimate_land_only/bulk_avg.tif')
# masklake <- terra::rast('/Users/junnawang/UCDLab/Biodiversity/data/climate/bioclimate_land_only/bio1_nolakes_moll.tif')
masklake <- terra::rast('/Users/junnawang/UCDLab/Biodiversity/data/climate/current/bio1.tif')
crs_moll <- "+proj=moll +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs"
#
# itime = 4
# issp  = 3
#
# seven climate variables, further simplify the code
id <-  c(1, 2, 4, 12, 15, 17, 19)  #   c(10, 11, 16)
#
for (itime in 4:length(times)) {
  for (issp in 1:length(ssps)) {
    print(paste0('ssp', ssps[issp]))
    path.write = paste0(root, times[itime], '/', ssps[issp], '/')
    path.read  = paste0(path.write, 'wc2.1_5m/')
    files <- list.files(path.read, full.names = T)
    nfile <- length(files)
    r     <- terra::rast(files)
    # Okay, I finally see how this works! This is a long list of single layer raster.
    # Furthermore, some GCM models does not call it bio**, but wc2**
    for (i in id) {
      series <- seq(from = i, to = nfile*19, by = 19)
      for (j in series) {
        print(mean(terra::values(r[[j]]), na.rm=T))
      }
      # project to molledue; I have to project first, resample, and then average, 1/2/2025; otherwise projection will miss some land grids. 
      bioc_project <- terra::project(r[[series]], crs_moll)
      bioc_project <- terra::resample(bioc_project, template)
      #
      bioc <- terra::app(bioc_project, mean)
      # mask inland water grids
      bioc <- terra::mask(bioc, masklake)
      # print(plot(bioc))
      # use the correct variable name
      names(bioc) <- paste0('bio', i, '_ESM_', ssps[issp], '_', times[itime])
      #
      writeRaster(bioc, filename = paste0(path.write, 'bio', i, '_ESM_', ssps[issp], '_', times[itime], '.tif'), overwrite=TRUE)
      print(paste0('Biovar', i))
    }
    # I should check if each model bio makes sense before averaging because they may make mistakes!
    for (igcm in 1:length(gcms)) {
      file  <- files[grepl(gcms[igcm], files)]
      r.gcm <- terra::rast(file)
      r.gcm <- terra::project(r.gcm[[id]],  crs_moll)
      r.gcm <- terra::resample(r.gcm, template)
      # mask inland water grids
      r.gcm <- terra::mask(r.gcm, masklake)
      if (igcm !=3) {
        name <- paste0('bio', id, '_', gcms[igcm], '_', ssps[issp], '_', times[itime])
      } else {
        name <- paste0('bio', id, '_MPIESM_', ssps[issp], '_', times[itime])
      }
      names(r.gcm) <- name
      #
      for (i in 1:length(id)) {
        writeRaster(r.gcm[[i]], filename = paste0(path.write, name[i], '.tif'), overwrite=TRUE)
      }
    }
  }
}

```


```{r get sampling bias map}
# bias map = species occurence record within a cell
# we assume that all the species we model is  a target group.

# download occurence data and merge them
library(BIEN)
library(sp)
library(maps)


occur <- BIEN_occurrence_species('Abies amabilis')   # I cannot do this step; because this package does not work. 
BIEN_occurrence_records_per_species(species = NULL) 


# the way he calcuates richness is really fast!

```


```{r try to download occurrence data}
library(BIEN)
#BIEN_occurrence_records_per_species(species = NULL) 
BIEN_occurrence_species("Abies amabilis")

```


```{r estimate sampling bias}
library(ks)
library(terra)
rm(list = ls())

root <- "C:/Users/jnawang/Box/Biodiversity/"
setwd(root)

occ <- readRDS('data/occurrence/sp_occr_records_all.Rds')
sample.effort <- terra::rast('data/occurrence/sample_effort_all.tif')

bio.long <- terra::rast('data/climate/history/wc2.1_5m/wc2.1_5m_bio_1.tif')
bio.moll <- terra::rast('SDM/preds/bios_pres/bio1.tif')

H    <- Hpi(x = occ[,c(3,2)])
fhat <- kde(x = occ[,c(3,2)], compute.cont = T, H=H, bgridsize = c(4320, 2160), xmin = c(-179.9583, -89.95833), xmax = c(179.9583, 89.95833))
plot(fhat)

sample.density <- bio.long
tmp <- matrix(0, nrow = 2160, ncol = 4320)
tmp[seq(2160, 1, -1), 1:4320] <- t(fhat$estimate)
tmp <- as.vector(t(tmp))
values(sample.density) <- tmp
sample.density <- terra::mask(sample.density, bio.long)
plot(sample.density)

sample.density <- terra::project(sample.density, bio.moll)
sample.density[sample.density < 0] <- 1.0e-10

writeRaster(sample.density, paste0(root, 'data/occurrence/sample_density.tif'), overwrite = T)

```


```{r check collinearity}
library(raster)
library(virtualspecies)
#
bios_pres <- list.files('C:/Users/jnawang/Box/Biodiversity/data/climate/history/wc2.1_5m/', pattern = ".tif$", full.names = TRUE)

bios_pres <- lapply(bios_pres, raster)
bios_pres <- stack(bios_pres)

removeCollinearity(
bios_pres,
multicollinearity.cutoff = 0.7,
select.variables = FALSE,
sample.points = FALSE,
nb.points = 10000,
plot = FALSE,
method = "kendall"
)
# other possible method: pearson, spearman, kendall
# If
# your variables are skewed or have outliers (e.g. when working with precipitation
# variables) you should favour the Spearman or Kendall methods.

# through this analysis, I decide to choose 7 bioclimate variables.
# bio1, bio2, bio4; bio12, bio15, bio17, bio19; and save the new variables

```



```{r using package to calculate bioclimate variables}
# this code is only used once; it takes long time to calculate this!
library(pbapply)
library(raster)      # they do not support terra!
library(dismo)
rm(list=ls())
#
dir <- 'C:/Users/jnawang/Box/Biodiversity/data/climate/1901_2022/'
# monthly min temperature
ncfname <- 'cru_ts4.07.1901.2022.tmn.dat.nc'
tmn <- raster::stack(paste0(dir, ncfname))

# monthly max temp
ncfname <- 'cru_ts4.07.1901.2022.tmx.dat.nc'
tmx <- stack(paste0(dir, ncfname))

# precipitation
ncfname <- 'cru_ts4.07.1901.2022.pre.dat.nc'
pre <- stack(paste0(dir, ncfname))

#
biovars.year <- list()
subfolder <- c('his1900', 'cur2000')
for (i in c(1:20, 71:110)) {
  print(i)
  irange  <- ((i-1)*12 + 1):(i*12)
  biovars.year[[i]] <- dismo::biovars(prec=pre[[irange]], tmin=tmn[[irange]], tmax=tmx[[irange]])
}
#
bio.id <- c(1, 12, 15, 17, 19, 2, 4)
biovar.his <- stack()
biovar.cur <- stack()
for (i in 1:length(bio.id)) {
  print(i)
  biovar.tmp <- stack()
  for (j in 1:20) {
    biovar.tmp <- addLayer(biovar.tmp, biovars.year[[j]][[bio.id[i]]])
  }
  biovar.his <- addLayer(biovar.his, mean(biovar.tmp)) 
  #
  biovar.tmp <- stack()
  for (j in 81:110) {
    biovar.tmp <- addLayer(biovar.tmp, biovars.year[[j]][[bio.id[i]]])
  }
  biovar.cur <- addLayer(biovar.cur, mean(biovar.tmp)) 
  #
} 
#
names(biovar.his) <- c('bio1', 'bio12', 'bio15', 'bio17', 'bio19', 'bio2', 'bio4')
names(biovar.cur) <- c('bio1', 'bio12', 'bio15', 'bio17', 'bio19', 'bio2', 'bio4')
# I want to create the actual maps for all of these. 
writeRaster(biovar.his, filename=paste0(dir, subfolder[1], '/7biovar_30min.tif'), overwrite=TRUE)
writeRaster(biovar.cur, filename=paste0(dir, subfolder[2], '/7biovar_30min.tif'), overwrite=TRUE)
##### finish the calculation
```


```{r scaling down historical maps}
# here is the way of scaling down. 
# bio1: +- changes; bio2: +- changes; bio12: +- changes; bio17: +- changes; bio19: +- changes
# bio4: ratio; bio15: ratio
#
###obtain new bio-vars
dir <- 'C:/Users/jnawang/Box/Biodiversity/data/climate/1901_2022/'
biovar.his <- terra::rast(paste0(dir, 'his1900/7biovar_30min.tif'))
biovar.cur <- terra::rast(paste0(dir, 'cur2000/7biovar_30min.tif')) 
# bio1
bio1 <- terra::rast('C:/Users/jnawang/Box/Biodiversity/data/climate/current/bio1.tif')
tmp  <- terra::project(biovar.his[[1]] - biovar.cur[[1]], "+proj=moll")
tmp  <- terra::resample(tmp, bio1)
bio1.his <- tmp + bio1
names(bio1.his) <- 'bio1'
plot(bio1)
plot(bio1.his)
# bio2
bio2 <- terra::rast('C:/Users/jnawang/Box/Biodiversity/data/climate/current/bio2.tif')
tmp  <- terra::project(biovar.his[[6]] - biovar.cur[[6]], "+proj=moll")
tmp  <- terra::resample(tmp, bio2)
bio2.his <- tmp + bio2
names(bio2.his) <- 'bio2'
plot(bio2)
plot(bio2.his)
# bio12
bio12 <- terra::rast('C:/Users/jnawang/Box/Biodiversity/data/climate/current/bio12.tif')
tmp   <- terra::project(biovar.his[[2]] - biovar.cur[[2]], "+proj=moll")
tmp   <- terra::resample(tmp, bio12)
bio12.his <- tmp + bio12
names(bio12.his) <- 'bio12'
plot(bio12)
plot(bio12.his)
# bio17
bio17 <- terra::rast('C:/Users/jnawang/Box/Biodiversity/data/climate/current/bio17.tif')
tmp   <- terra::project(biovar.his[[4]] - biovar.cur[[4]], "+proj=moll")
tmp   <- terra::resample(tmp, bio17)
bio17.his <- tmp + bio17
names(bio17.his) <- 'bio17'
plot(bio17)
plot(bio17.his)
# bio19
bio19 <- terra::rast('C:/Users/jnawang/Box/Biodiversity/data/climate/current/bio19.tif')
tmp   <- terra::project(biovar.his[[5]] - biovar.cur[[5]], "+proj=moll")
tmp   <- terra::resample(tmp, bio19)
bio19.his <- tmp + bio19
names(bio19.his) <- 'bio19'
plot(bio19)
plot(bio19.his)
#
#
# bio4
bio4 <- terra::rast('C:/Users/jnawang/Box/Biodiversity/data/climate/current/bio4.tif')
tmp   <- terra::project(biovar.his[[7]] / biovar.cur[[7]], "+proj=moll")
tmp   <- terra::resample(tmp, bio4)
bio4.his <- tmp * bio4
names(bio4.his) <- 'bio4'
plot(bio4)
plot(bio4.his)
# bio15
bio15 <- terra::rast('C:/Users/jnawang/Box/Biodiversity/data/climate/current/bio15.tif')
tmp   <- terra::project(biovar.his[[3]] / biovar.cur[[3]], "+proj=moll")
tmp   <- terra::resample(tmp, bio15)
bio15.his <- tmp * bio15
names(bio15.his) <- 'bio15'
plot(bio15)
plot(bio15.his)
#

  writeRaster(bio1.his, filename=paste0(dir, 'his1900/bio1.tif'), overwrite=TRUE)
  writeRaster(bio2.his, filename=paste0(dir, 'his1900/bio2.tif'), overwrite=TRUE)
  writeRaster(bio4.his, filename=paste0(dir, 'his1900/bio4.tif'), overwrite=TRUE)
  writeRaster(bio12.his, filename=paste0(dir, 'his1900/bio12.tif'), overwrite=TRUE)
  writeRaster(bio15.his, filename=paste0(dir, 'his1900/bio15.tif'), overwrite=TRUE)
  writeRaster(bio17.his, filename=paste0(dir, 'his1900/bio17.tif'), overwrite=TRUE)
  writeRaster(bio19.his, filename=paste0(dir, 'his1900/bio19.tif'), overwrite=TRUE)
  
```


```{r get new current climate map 1981-2010}
library(raster)
library(terra)
# this will take lots of times 
dir <- '/Users/junnawang/UCDLab/Biodiversity/data/climate/current/'
#
stack.tmax <- stack()
files.zip  <- list.files(dir, pattern='wc2.1_cruts4.06_5m_tmax', full.names = T)
for (file in files.zip) {
  # raster stack
  stack.tmax <- addLayer(stack.tmax, raster::stack(unzip(file)))  
}
print('read tmax done!')

stack.tmin <- stack()
files.zip  <- list.files(dir, pattern='wc2.1_cruts4.06_5m_tmin', full.names = T)
for (file in files.zip) {
  # raster stack
  stack.tmin <- addLayer(stack.tmin, raster::stack(unzip(file)))  
}
print('read tmin done!')
##
stack.prec <- stack()
files.zip  <- list.files(dir, pattern='wc2.1_cruts4.06_5m_prec', full.names = T)
for (file in files.zip) {
  # raster stack
  stack.prec <- addLayer(stack.prec, raster::stack(unzip(file)))  
}
print('read prec done!')
##
##
for (i in c(1:31)) {
  print(i)
  irange  <- ((i-1)*12 + 1):(i*12)
  biovars.year[[i]] <- dismo::biovars(prec=stack.prec[[irange]], tmin=stack.tmin[[irange]], tmax=stack.tmax[[irange]])
}
print('biovar each year done!')
#
# read yearly biovars, if I do not want to recalculate these maps
files.yearly <- list.files('/Users/junnawang/UCDLab/Biodiversity/data/climate/current/', pattern='^yearly_biovariables_', full.names = T)

biovars.year <- list()
for (j in 1:31) {
  biovars.year[[j]] <- raster::stack(files.yearly[j])
}
#
#
bio.id <- c(1, 12, 15, 17, 19, 2, 4)
biovar.cur <- stack()
for (i in 1:length(bio.id)) {
  print(i)
  biovar.tmp <- stack()
  for (j in 1:31) {
    biovar.tmp <- addLayer(biovar.tmp, biovars.year[[j]][[bio.id[i]]])
  }
  biovar.cur <- addLayer(biovar.cur, mean(biovar.tmp)) 
  #
} 
print('biovar multiple year mean done!')
#
# convert to mollel and 5 min
template <- terra::rast('/Users/junnawang/UCDLab/Biodiversity/data/climate/bioclimate_land_only/bulk_avg.tif')
masklake <- terra::rast('/Users/junnawang/UCDLab/Biodiversity/data/climate/bioclimate_land_only/bio1_nolakes_moll.tif')
crs_moll <- "+proj=moll +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs"
#
biovar.cur <- terra::project(terra::rast(biovar.cur), crs_moll)
biovar.cur <- terra::resample(biovar.cur, template)
biovar.cur <- terra::mask(biovar.cur, masklake)
#
names <- c('bio1', 'bio12', 'bio15', 'bio17', 'bio19', 'bio2', 'bio4')
names(biovar.cur) <- names
# I want to create the actual maps for all of these. 
for (i in 1:length(names)) {
  writeRaster(biovar.cur[[i]], filename=paste0(dir, names[i], '.tif'), overwrite=TRUE)
}
##

```


```{r compare current and future maps to have the same land grids}
library(terra)
# 
# 2/11/2025: most of the maps have the same number of land grid cells, particularly ESM models, but a few of them are not.  
biovar <- c('bio1', 'bio12', 'bio15', 'bio17', 'bio19', 'bio2', 'bio4')
bio_current <- terra::rast(paste0('/Users/junnawang/UCDLab/Biodiversity/data/climate/current/', biovar, '.tif'))
#
bio_future <- terra::rast('/Users/junnawang/UCDLab/Biodiversity/data/climate/future/2081-2100/126/bio12_ESM_126_2081-2100.tif')
#
sum(!is.na(terra::values(bio_future)))
#
sum(!is.na(terra::values(bio_current[[1]])))
#
plot(bio_current[[1]])
plot(bio_future)
#
bio1_near_current <- terra::rast('/Users/junnawang/UCDLab/Biodiversity/data/climate/near_current/wc2.1_5m_bio_12.tif')
bio1_near_current_moll <- terra::project(bio1_near_current, '+proj=moll +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs')
#
bio1_near_current_moll <- terra::resample(bio1_near_current_moll, bio_current[[1]])
#
plot(bio_current[[2]] - bio1_near_current_moll)
#
plot(bio_future - bio_current[[2]])
#
plot(bio_future - bio1_near_current_moll)
#
```



```{r compare with current, future, and history}
library(ggplot2)
# sample points
template <- terra::rast(paste0('C:/Users/jnawang/Box/Biodiversity/data/climate/current/bio1.tif'))
#
cell.id <- which(!is.na(terra::values(template)))
cell.id.rand <- sample(cell.id, 20000)

#
biovar <- c('bio1', 'bio12', 'bio15', 'bio17', 'bio19', 'bio2', 'bio4')
for (i in 1:length(biovar)) {
  map_current <- terra::rast(paste0('C:/Users/jnawang/Box/Biodiversity/data/climate/current/', biovar[i], '.tif'))
  # map_current0 <- terra::rast(paste0('C:/Users/jnawang/Box/Biodiversity/SDM/preds/bios_pres/', biovar[i], '.tif'))
  #
  #  plot(map_current1 - map_current0) 
  map_future  <- terra::rast(paste0('C:/Users/jnawang/Box/Biodiversity/data/climate/future/2081-2100/245/', biovar[i], '_ESM_245_2081-2100.tif'))
  map_history <- terra::rast(paste0('C:/Users/jnawang/Box/Biodiversity/data/climate/1901_2022/his1900/', biovar[i], '_1900.tif'))
  #
  dif_cur_fut <- na.omit(terra::values(map_future - map_current)[cell.id.rand])
  dif_cur_his <- na.omit(terra::values(map_current - map_history)[cell.id.rand])
  #
  # xrange=quantile(c(terra::values(dif_cur_fut)[cell.id.rand], terra::values(dif_cur_his)[cell.id.rand]), prob=c(0.01, 0.99), na.rm=T)
  # #
  # p1 <- hist(terra::values(dif_cur_fut)[cell.id.rand], na.rm=T, freq=T, breaks = 50, xlim=c(xrange[1], xrange[2]))
  # p2 <- hist(terra::values(dif_cur_his)[cell.id.rand], na.rm=T, freq=T, breaks = 50, xlim=c(xrange[1], xrange[2]))
  # #
  # plot(p1, col=rgb(0,0,1,1/4), xlim=c(xrange[1], xrange[2]))
  # plot(p2, col=rgb(1,0,0,1/4), xlim=c(xrange[1], xrange[2]), add=T)
  #
  bio.dif <- data.frame(x=c(dif_cur_fut, dif_cur_his), period=c(rep("Diffences between future and current", length(dif_cur_fut)), rep("Diffences between current and history", length(dif_cur_his))))
  bio.dif$period <- as.factor(bio.dif$period)
p <-  ggplot(data=bio.dif, aes(x=x, color=period)) +
    geom_density() + 
    labs(x=biovar[i], y='Probability density') +
    theme_minimal() +
    theme(legend.position = c(0.5, 0.8))
print(p)
}
# only bio1 and bio2 have great differences between the two periods. 

```
